### ISSUE TITLE
Add option to playback PCAP

### ISSUE THREAD

**Issue by crashza** [negbie/hammerHEP#2]
Hi It would be really nice if you where able to playback any pcap file and also an option to loop the pcap file for stress testing.

I noticed my results with hammerhep are slightly easier on IO when stress testing than my production traffic thus grabbing a 1 minute pcap from production traffic and stress testing would be a great feature.

Thanks for the cool tool

**Comment by negbie** [comment]
You should be able to do this whith heplify. Therefore I added in heplify the flags
-rf     point to your pcap file
-rs    will read pcap as fast as possible but use the timestamp from the pcap
-lp    loop count

Just use them as you need and like.

**Comment by crashza** [comment]
thanks for you quick reply. Thats exactly what i need just needed to RTFM :)
